require File.expand_path(File.dirname(__FILE__) + '/spec_helper')

describe "AsciiTable" do
  before(:each) do
    @at = AsciiTable.new
  end
  it "should draw simple table" do
    data = [['foo', 'bar'], [1, 2]]
    @at.data = data
    @at.generated = false
    @at.build.should == " ___________\n| foo | bar |\n| 1   | 2   |\n|_____|_____|\n"
  end
  it "should draw simple table with lineup" do
    data = [['foo', 'bar'], [1, 2]]
    @at.data = data
    @at.lineup = true
    @at.generated = false
    @at.build.should == " ___________\n| foo | bar |\n|-----|-----|\n| 1   | 2   |\n|_____|_____|\n"
  end
  it "should draw simple table with header" do
    data = [['foo', 'bar'], [1, 2]]
    @at.data = data
    @at.header = true
    @at.generated = false
    @at.build.should == " ___________\n| foo | bar |\n|=====|=====|\n| 1   | 2   |\n|_____|_____|\n"
  end
  it "should draw simple table with header, lineup without generated note" do
    data = [['foo', 'bar', 'woot'], [1, 2, 3], [4, 5, 6]]
    @at.data = data
    @at.header = true
    @at.lineup = true
    @at.build.should == " __________________\n| foo | bar | woot |\n|=====|=====|======|\n| 1   | 2   | 3    |\n|-----|-----|------|\n| 4   | 5   | 6    |\n|_____|_____|______|\n"
  end
  it "should draw simple table with header, lineup with generated note" do
    data = [['foo', 'bar', 'woot', 'mega', 'candy'], [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
    @at.data = data
    @at.header = true
    @at.lineup = true
    @at.build.should == " _________________________________\n| foo | bar | woot | mega | candy |\n|=====|=====|======|======|=======|\n| 1   | 2   | 3    | 4    | 5     |\n|-----|-----|------|------|-------|\n| 6   | 7   | 8    | 9    | 10    |\n|---------------------------------|\n|    Generated by ascii-table gem |\n|_________________________________|\n"
  end
  it "should draw big table with header and lineup" do
    data = [['Orange', 'Green', 'Yello', 'Blue', 'Pink'], [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
    @at.data = data
    @at.header = true
    @at.lineup = true
    @at.generated = false
    @at.build.should == " ______________________________________\n| Orange | Green | Yello | Blue | Pink |\n|========|=======|=======|======|======|\n| 1      | 2     | 3     | 4    | 5    |\n|--------|-------|-------|------|------|\n| 6      | 7     | 8     | 9    | 10   |\n|--------|-------|-------|------|------|\n| 11     | 12    | 13    | 14   | 15   |\n|--------|-------|-------|------|------|\n| 16     | 17    | 18    | 19   | 20   |\n|________|_______|_______|______|______|\n"
  end
end
